FeiraProfissões/FeiraProfissões/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeiraProfissões.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a4c265_feira19Entities : DbContext
    {
        public db_a4c265_feira19Entities()
            : base("name=db_a4c265_feira19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_avaliacao> tb_avaliacao { get; set; }
        public virtual DbSet<tb_log_navegacao> tb_log_navegacao { get; set; }
    }
}

FeiraProfissões/FeiraProfissões/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\infob02\Source\Repos\projeto-qr-code\FeiraProfissões\FeiraProfissões\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

FeiraProfissões/FeiraProfissões/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

FeiraProfissões/FeiraProfissões/Models/tb_avaliacao.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeiraProfissões.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_avaliacao
    {
        public int id_avaliacao { get; set; }
        public int qt_estrelas { get; set; }
        public Nullable<System.DateTime> dt_avaliacao { get; set; }
        public string ip_address { get; set; }
    }
}

FeiraProfissões/FeiraProfissões/Models/tb_log_navegacao.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeiraProfissões.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_navegacao
    {
        public int id_log { get; set; }
        public Nullable<System.DateTime> dt_log { get; set; }
        public string nm_page { get; set; }
        public string ip_address { get; set; }
    }
}

FeiraProfissões/FeiraProfissões/Controllers/Feira/FeiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeiraProfissões.Controllers.Feira
{
    public class FeiraController : Controller
    {
        Business.FeiraBusiness business = new Business.FeiraBusiness();

        public ActionResult Index()
        {
            Models.tb_log_navegacao log = new Models.tb_log_navegacao();

            log.dt_log = DateTime.Now;
            log.nm_page = "Página Inicial";
            log.ip_address = Request.UserHostAddress;

            business.InserirLog(log);

            return View();
        }

        public ActionResult Avaliacao()
        {
            Models.tb_log_navegacao log = new Models.tb_log_navegacao();

            log.dt_log = DateTime.Now;
            log.nm_page = "Avaliação";
            log.ip_address = Request.UserHostAddress;

            business.InserirLog(log);

            return View();
        }

        [HttpPost]
        public ActionResult Avaliacao(int estrela)
        {
            Models.tb_avaliacao avaliacao = new Models.tb_avaliacao();
            avaliacao.dt_avaliacao = DateTime.Now;
            avaliacao.qt_estrelas = estrela;
            avaliacao.ip_address = Request.UserHostAddress;

            business.Inserir(avaliacao);

            return View();
        }

        public ActionResult SegundoAndar()
        {
            Models.tb_log_navegacao log = new Models.tb_log_navegacao();

            log.dt_log = DateTime.Now;
            log.nm_page = "Segundo Andar";
            log.ip_address = Request.UserHostAddress;

            business.InserirLog(log);

            return View();
        }

        public ActionResult PrimeiroAndar()
        {
            Models.tb_log_navegacao log = new Models.tb_log_navegacao();

            log.dt_log = DateTime.Now;
            log.nm_page = "Primeiro Andar";
            log.ip_address = Request.UserHostAddress;

            business.InserirLog(log);

            return View();
        }

        public ActionResult Terreo()
        {
            Models.tb_log_navegacao log = new Models.tb_log_navegacao();

            log.dt_log = DateTime.Now;
            log.nm_page = "Térreo";
            log.ip_address = Request.UserHostAddress;

            business.InserirLog(log);

            return View();
        }
        public ActionResult TerceiroAndar()
        {
            Models.tb_log_navegacao log = new Models.tb_log_navegacao();

            log.dt_log = DateTime.Now;
            log.nm_page = "Terceiro Andar";
            log.ip_address = Request.UserHostAddress;
            business.InserirLog(log);

            return View();
        }
    }
}

FeiraProfissões/FeiraProfissões/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeiraProfissões.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FeiraProfissões/FeiraProfissões/Views/Feira/Avaliacao.cshtml
@model FeiraProfissões.Models.tb_avaliacao

    @{
        ViewBag.Title = "Avaliacao";
    }

    <script>
        function EnviarAvaliacao() {
            var form = document.getElementById('formAvaliacao');
            form.submit();

            var popup = document.getElementById("myPopup");
            popup.classList.toggle("show");
        }
    </script>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/Site.css">

<div class="imagemAvaliacao">
</div>    

    <h1 style="text-align:center; color:black"><b>O que Achou da Feira?</b></h1>

    @using (Html.BeginForm("Avaliacao", "Feira", FormMethod.Post, new { id = "formAvaliacao" }))
    {
        @Html.AntiForgeryToken()
        <center>

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="popup">


                    <div class="estrelas">
                        <input type="radio" id="vazio" name="estrela" value="" checked />

                        <label for="estrela_um"><i class="fa"></i></label>
                        <input type="radio" id="estrela_um" name="estrela" value="1" onclick="EnviarAvaliacao();" />
                        <span class="popuptext" id="myPopup">Obrigado pela Avaliação</span>

                        <label for="estrela_dois"><i class="fa"></i></label>
                        <input type="radio" id="estrela_dois" name="estrela" value="2" onclick="EnviarAvaliacao();" />

                        <label for="estrela_tres"><i class="fa"></i></label>
                        <input type="radio" id="estrela_tres" name="estrela" value="3" onclick="EnviarAvaliacao();" />

                        <label for="estrela_quatro"><i class="fa"></i></label>
                        <input type="radio" id="estrela_quatro" name="estrela" value="4" onclick="EnviarAvaliacao();" />

                        <label for="estrela_cinco"><i class="fa"></i></label>
                        <input type="radio" id="estrela_cinco" name="estrela" value="5" onclick="EnviarAvaliacao();" />

                    </div>
                    @Html.ValidationMessageFor(model => model.qt_estrelas, "", new { @class = "text-danger" })
                </div>
            </div>
        </center>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

FeiraProfissões/FeiraProfissões/Views/Feira/Index.cshtml
@{
                /**/

                ViewBag.Title = "Página Inicial";
}

<link href="~/Content/Site.css" rel="stylesheet" />

<div class="slideshow-container">

    <div class="mySlides fade" style="background-image:url(../../Imagens/feiraLogo.jpeg)">
    </div>

    <div class="mySlides fade" style="background-image:url('../../Imagens/Predio Frei.jpg')">
    </div>
    
    <div class="mySlides fade" style="background-image: url(https://acaonsfatima.org.br/wp-content/uploads/2018/11/plateia.jpg)">
    </div>
</div>

<div style="text-align:center" class="navegador">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
</div>

<div class="entry-content">
    <p><strong>No dia 21 de Setembro de 2019</strong>, o <strong>primeiro evento</strong> organizado por nós especialmente para você que tem dúvidas sobre como funciona o <strong>Mundo do Trabalho</strong>, como se comportar, o que cada área realiza e muitas outras curiosidades que te ajudarão a conhecer o ambiente profissional!</p>
    <p>Teremos vários <strong>temas especiais</strong> com atividades interativas de cada curso (<strong>inclusive o CEDESP</strong>), <strong>Sebo</strong> com livros de diversos assuntos e livros <strong>escritos pelo próprio Frei Xavier</strong>, além dos stands de alguns dos nossos parceiros.</p>
    <p>Veja nossa programação, marque a data na sua agenda e chame todos para participar.</p>
    <p><strong>Evento gratuito! Não perca!</strong></p>
    <p>&nbsp;</p>
</div>

<div class="salas">

    <a href='@Url.Action("Terreo", "Feira")'>
        <div id="terreo">
            Térreo
        </div>
    </a>

    <a href='@Url.Action("PrimeiroAndar", "Feira")'>
        <div id="primeiroAndar">
            1º Andar
        </div>
    </a>

    <a href='@Url.Action("SegundoAndar", "Feira")'>
        <div id="segundoAndar">
            2º Andar
        </div>
    </a>

    <a href='@Url.Action("TerceiroAndar", "Feira")'>
        <div id="terceiroAndar">
            3º Andar
        </div>
    </a>

</div>

<br />

<h1 style="color: black; text-align:center;">Parceiros</h1>

<div id="parceiros">
    <img id="p1" src="~/Imagens/logo.png" />
    <img id="p2" src="https://www.perfilcontabil.com.br/wp-content/uploads/2018/08/Prefeitura-de-S%C3%A3o-Paulo.png" />
    <img id="p3" src="https://images.sympla.com.br/5c964feab47ab.png" />
    <img id="p4" src="https://whatsrel.com.br/wp-content/uploads/2019/08/stb-logo-c%C3%B3pia.jpg" />
    <img id="p5" src="https://www.expoopticabrasil.com/wp-content/uploads/2019/01/cropped-logo.png" />
    <img id="p6" src="http://www.casion.com.br/img/social_logo_on.jpg" />
    <img id="p7" src="http://159.203.175.70/wp-content/uploads/2015/04/logo-saopauloopencentre.jpg" />
    <img id="p8" src="https://yt3.ggpht.com/a/AGF-l78k32uLjygj1iEGTzKhBVzwhEv3kit9f-OqoA=s900-c-k-c0xffffffff-no-rj-mo" />
    <img id="p9" src="http://raizesds.com.br/wp-content/uploads/2016/10/sebrae-logo.jpg" />
    <img id="p10" src="https://www.viacaograjau.com.br/wp-content/uploads/2019/05/viacao-grajau-logotipo.png" />
    <img id="p11" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRqvHlDuH2RyUjw3YoP9oT7a-oIOpCrwO7WIvhWcBivNMuE3FF" />
</div>

<br />

<p>&nbsp;</p>
<h1 style="color: black; text-align:center;">Como Chegar</h1>
<p>&nbsp;</p>

<iframe src="https://maps.google.com/maps?q=av.%20coronel%20octaviano%20costa%2C%20463&t=&z=15&ie=UTF8&iwloc=&output=embed" height="450" frameborder="0" style="border:0; width:110%; margin-left:-15px" allowfullscreen="" ;></iframe>

<script>
    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) { slideIndex = 1 }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
        setTimeout(showSlides, 3000);
    }
</script>

FeiraProfissões/FeiraProfissões/Views/Feira/PrimeiroAndar.cshtml
@{
    ViewBag.Title = "PrimeiroAndar";
}

<div class="andar_content">
    
    <link href="~/Content/andar1.css" rel="stylesheet" />
    <div class="img">
        <div class="andar">1º Andar</div>
        <img src="~/Imagens/img1Andar.jpg" style="width:100%" />
    </div>

    <div class="frase">
        Neste andar teremos diversas apresentações e exibições de projetos voltados para a área
        de Informática e Administração, é uma ótima opção para aqueles que gostam de informática ou querem aprender um pouco 
        sobre contabilidade e empreendedorismo.
    </div>
    <div class="Info">
        <figure class="figura1">
            <img src="~/Imagens/curso-de-informatica-basica.jpg" width="150" height="150" alt="Imagem Xis">
        </figure>

        <center class="sala">
            <div><b>Sala 16</b></div>
        </center>
        <br />
        <div class="texto">
            Será realizada a exibição de um projeto feito pelos nossos alunos de T.I.
            que montaram usando um Arduino! Na mesma sala, os alunos darão pequenas aulas sobre programação
            para aqueles que estiverem interessados e curiosos sobre como funciona essa gigantesca área de atuação, além de 
            jogos programados por eles. Os visitantes estão convidados a jogar conosco!
        </div>
        <br />
        <br />
        <center class="fonte">
            <div><b>"Projeto Arduino e Projetos de Programação"</b></div>
        </center>
    </div>

    <div class="Contab">
        <figure class="figura2">
            <img src="~/Imagens/contabilidade.jpg" width="150" height="150" alt="Imagem Xis">
        </figure>

        <center class="sala">
            <div><b>Sala 17</b></div>
        </center>
        <br />
        <div class="texto">
            Na sala 17 será apresentado um projeto sobre Contabilidade e Recursos Humanos, onde os visitantes
            terão a oportunidade de tirar dúvidas e aprender um pouco mais sobre essas áreas.

        </div>
        <br />
        <br />
        <center class="fonte">
            <div><b>"Paixão por vencer em diferentes perspectivas visão 4.0"</b></div>
        </center>
    </div>

    <div class="Empreen">
        <figure class="figura1">
            <img src="~/Imagens/empreendedorismo-ideia-nova.jpg" width="150" height="150" alt="Imagem Xis">
        </figure>

        <center class="sala">
            <div><b>Sala 18</b></div>
        </center>
        <br />
        <div class="texto">
            Os nossos alunos de Administração apresentarão um projeto inspirador e motivacional sobre empreendedorismo, onde estarão incentivando
        e dando dicas sobre o assunto, mostrando que usando o que estiver ao seu alcance, mesmo que seja pouco, você tem capacidade para
        gerar muito lucro.
        </div>
        <br />
        <br />
        <center class="fonte">
            <div><b>"Comece de onde você está. Use o que tiver. Faça o que você puder."</b></div>
        </center>
    </div>

   
    <br />

</div>

FeiraProfissões/FeiraProfissões/Views/Feira/SegundoAndar.cshtml
@{
    ViewBag.Title = "SegundoAndar";
}

<div class="andar_content">
    
    <link href="~/Content/andar2.css" rel="stylesheet" />
    <div class="img">
        <div class="andar">2º Andar</div>
        <img src="~/Imagens/img2Andar.jpg" style="width:100%" />
    </div>

    <div class="frase">
        Neste andar você terá uma variedade de atividades: aprender sobre o processo de edição,
        elaborar o seu currículo, fazer o teste vocacional, carteira de trabalho e ainda assistir um Talk
        Show sobre a carreira do Secretariado.
    </div>
    <div class="Comunicação">
        <figure class="figura1">
            <img src="~/Imagens/Comu.jpg" width="150" height="150">
        </figure>

        <center class="sala">
            <div><b>Sala 21</b></div>
        </center>
        <br />
        <div class="texto">
            Venha conhecer nossa turma de Comunicação Visual, 
            aqui você poderá acompanhar todo o processo de desenho 
            e edição até de uma caricatura por exemplo!
            Você terá a chance de ter uma noção melhor de tudo que 
            acontece aqui no curso de comunicação visual.
        </div>
        <br />
        <br />
        <center class="fonte">
            <div><b>"O ver e o entender, o idealizar e o realizar"</b></div>
        </center>
    </div>

    <div class="Curriculo">
        <figure class="figura2">
            <img src="~/Imagens/como-fazer-um-curriculo-bem-feito-790x527.jpg" width="150" height="150">
        </figure>

        <center class="sala">
            <div><b>Sala 22</b></div>
        </center>
        <br />
        <div class="texto">
            Em colaboração com a CEDESP, os visitantes terão a oportunidade de montar o seu currículo!
            Isso mesmo, pessoas de todas as idades poderão tirar suas dúvidas, não perca essa chance! 
        </div>
        <br />
        <br />
        <center class="fonte">
            <div><b>"Maximizando oportunidades"</b></div>
        </center>
    </div>

    <div class="CAT">
        <figure class="figura1">
            <img src="~/Imagens/Vocação.jpg" width="150" height="150">
        </figure>

        <center class="sala">
            <div><b>Sala 23</b></div>
        </center>
        <br />
        <div class="texto">
            O CAT (Centro de Apoio ao Trabalhador) estará realizando a emissão de carteira de trabalho e
            encaminhando o adulto para entrevista. Se você ainda não tem certeza do que cursar, ou quer
            uma segunda opinião sobre o que você já planeja fazer, poderá fazer o teste vocacional que irá
            ajudar bastante e lhe aconselhar a tomar uma decisão melhor.
        </div>
        <br />
        <br />
        <center class="fonte">
            <div><b>"A melhor escolha é aquela consciente!"</b></div>
        </center>
    </div>

    <div class="BatePapo">
        <figure class="figura2">
            <img src="~/Imagens/BatePapo.jpg" width="150" height="150">
        </figure>

        <center class="sala">
            <div><b>Sala 24</b></div>
        </center>
        <br />
        <div class="texto">
            Aqui você poderá assistir e até participar de um Talk Show! Isso mesmo, profissionais de Secretariado estarão aqui e falarão um pouco sobre a área, segredos,
            técnicas e muito mais. Claro que vai ser algo bem interativo com o público, não perca a chance
            e venha dar uma olhada.
        </div>
        <br />
        <br />
        <center class="fonte">
            <div><b>"Construindo Histórias de Sucesso"</b></div>
        </center>
    </div>
    <br />

</div>

FeiraProfissões/FeiraProfissões/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FeiraProfissões/FeiraProfissões/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FeiraProfissões/FeiraProfissões/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FeiraProfissões/FeiraProfissões/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Feira de Profissões INSF</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <center>
        <div class="navbar navbar-inverse navbar-fixed-top" id="navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span class="navbar-brand" style="color:lightgray;">Feira de Profissões ISNSF</span>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Página Inicial", "Index", "Feira", new { style = "color:lightgray;" })</li>
                        <li>@Html.ActionLink("Térreo", "Terreo", "Feira", new { style = "color:lightgray;" })</li>
                        <li>@Html.ActionLink("1º Andar", "PrimeiroAndar", "Feira", new { style = "color:lightgray;" })</li>
                        <li>@Html.ActionLink("2º Andar", "SegundoAndar", "Feira", new { style = "color:lightgray;" })</li>
                        <li>@Html.ActionLink("3º Andar", "TerceiroAndar", "Feira", new { style = "color:lightgray;" })</li>
                        <li>@Html.ActionLink("Avaliação", "Avaliacao", "Feira", new { style = "color:lightgray;" })</li>
                    </ul>
                </div>
            </div>
        </div>
    </center>

    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    <footer id="colophon">
        <br />
        <div style="float:right; margin-right:40px;">
            <h6 style="font-size:14px; margin-left:40px">Menu</h6>
            <ul>
                <li>@Html.ActionLink("Térreo", "Terreo", "Feira", new { style = "color:lightgray;" })</li>
                <li>@Html.ActionLink("1º Andar", "PrimeiroAndar", "Feira", new { style = "color:lightgray;" })</li>
                <li>@Html.ActionLink("2º Andar", "SegundoAndar", "Feira", new { style = "color:lightgray;" })</li>
                <li>@Html.ActionLink("3º Andar", "TerceiroAndar", "Feira", new { style = "color:lightgray;" })</li>
            </ul>
        </div>

        <div style="text-align:left; color:lightgray">
            <h6 style="font-size:14px; margin-left: 40px;">Cursos</h6>
            <ul>
                <li><a href="https://acaonsfatima.org.br/cursos/implantacao-de-redescopiar/" style="color:lightgray">Inglês - Nível Básico ao Intermediário</a></li>
                <li><a href="https://acaonsfatima.org.br/cursos/eletromecanica/" style="color:lightgray">Qualificação em Eletromecânica</a></li>
                <li><a href="https://acaonsfatima.org.br/cursos/eletrotecnica/" style="color:lightgray">Qualificação em Eletrotécnica</a></li>
                <li><a href="https://acaonsfatima.org.br/cursos/secretariado/" style="color:lightgray"> Técnico em Secretariado</a></li>
                <li><a href="https://acaonsfatima.org.br/cursos/administracao-de-empresas/" style="color:lightgray">Técnico em Administração</a></li>
                <li><a href="https://acaonsfatima.org.br/cursos/informatica/" style="color:lightgray">Técnico em Informatica</a></li>
                <li><a href="https://acaonsfatima.org.br/cursos/comunicacao-visual/" style="color:lightgray">Técnico em Comunicação Visual</a></li>

            </ul>
        </div>

        <br />

        <h6 style="font-size:14px; margin-left: 20px;">Siga-nos</h6>
        <div style="margin-left:20px; display: flex">
            <div>
                <a href="https://www.facebook.com/Instituto-Social-Nossa-Senhora-de-F%C3%A1tima-230903353703049/" target="_blank" title="Facebook">
                    <img src="https://escolapinheiro.com.br/wp-content/uploads/2018/09/if_facebook_circle_color_107175.png">
                </a>
            </div>
            <div>
                <a href="https://twitter.com/?lang=pt-br" target="_blank" title="Twitter">
                    <img src="https://escolapinheiro.com.br/wp-content/uploads/2018/09/if_twitter_circle_color_107170.png">
                </a>
            </div>
            <div class="pr-2">
                <a href="https://www.instagram.com/acaonsfatima/?hl=pt-br" target="_blank" title="Instagram">
                    <img src="https://escolapinheiro.com.br/wp-content/uploads/2019/03/Webp.net-resizeimage-2.png">
                </a>
            </div>
        </div>

        <br />

        <div>
            <img style="margin-left: 20px" class="pr-2" src="https://escolapinheiro.com.br/wp-content/themes/escola-pinheiro/dist/images/phone.png">
            <span class="d-inline-block">
                (011) 5687-8876
            </span>
        </div>

        <br />

    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>